export function getVariables() {
	return [
		{ variableId: 'fader', name: 'Master fader level (0.0 - 10.0)' },
		{ variableId: 'fader_raw', name: 'Master fader level raw (0 - 100, tenths)' },
		{ variableId: 'muted', name: 'Master mute state' },
		{ variableId: 'format', name: 'Current format name' },
		{ variableId: 'monitor_level', name: 'Monitor level (0 - 100)' },
		{ variableId: 'monitor_mute', name: 'Monitor mute state' },
		{ variableId: 'power_state', name: 'Unit power state (On / Standby / Starting)' },
		{ variableId: 'temp1', name: 'Temperature H331 board (°C)' },
		{ variableId: 'temp2', name: 'Temperature H332 board (°C)' },
		{ variableId: 'temp3', name: 'Temperature H335 board (°C)' },
		{ variableId: 'power', name: 'Overall supply voltage status (OK/FAULT)' },
		{ variableId: 'power_faults', name: 'Boards with a supply voltage fault (empty = none)' },
		{ variableId: 'board_h331', name: 'Supply voltages H331 board (OK / FAULT / N/A)' },
		{ variableId: 'board_h332', name: 'Supply voltages H332 board (OK / FAULT / N/A)' },
		{ variableId: 'board_h335', name: 'Supply voltages H335 board (OK / FAULT / N/A)' },
		{ variableId: 'board_h336', name: 'Supply voltages H336 board (OK / FAULT / N/A)' },
		{ variableId: 'board_h338', name: 'Supply voltages H338 board (OK / FAULT / N/A)' },
		{ variableId: 'phantom', name: 'Microphone phantom power (On / Off)' },
		{ variableId: 'cpu_power', name: 'CPU supply (OK / FAULT)' },
		{ variableId: 'version', name: 'Device software version' },
		{ variableId: 'serial', name: 'Device serial number' },
	]
}
