blank_issues_enabled: true
contact_links:
  - name: Bitfocus Companion support
    url: https://github.com/bitfocus/companion/issues
    about: Issues with Companion itself, rather than with this module.
